### PR TITLE
Release notes typo fix

### PR DESCRIPTION
**Pull request by Danthar**
Pushed commit directly to dev by accident. This pr fixes a release notes typo. And serves as a placeholder for the actual update.
Last commit broke the Build on TC for some reason.

### CODE REVIEW

**Comment by Danthar** [comment]
Seems castle.windsor is not yet netcore compatible. Which causes issues when we use xunit here. 
https://github.com/castleproject/Windsor/issues/145

**Comment by heynickc** [comment]
@Danthar #6 looks like it fixed the issue with the build throwing that German error message.  It was hard coded into the .csproj so I removed it.

**Comment by heynickc** [comment]
@Danthar Sorry, nevermind that.  It's throwing a different error message now, working on it

**Comment by heynickc** [comment]
@Danthar ok, fixed #6 we should be good.

**Pull request merged**
